// <auto-generated />
namespace WebShop.DataAccess.SQL.Migrations.webshop
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class basketAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basketAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201906180744267_basketAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
